[package]
name = "ckb-network"
version = "0.39.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "ckb network implementation"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
rand = "0.6"
serde = { version = "1.0", features = ["derive"] }
ckb-util = { path = "../util", version = "= 0.39.0-pre" }
ckb-stop-handler = { path = "../util/stop-handler", version = "= 0.39.0-pre" }
ckb-logger = { path = "../util/logger", version = "= 0.39.0-pre" }
ckb-app-config = { path = "../util/app-config", version = "= 0.39.0-pre" }
tokio = { version = "0.2.11", features = ["sync", "macros"] }
tokio-util = { version = "0.3.0", features = ["codec"] }
futures = "0.3"
faketime = "0.2.0"
lazy_static = { version = "1.3.0", optional = true }
bs58 = { version = "0.3.0", optional = true }
sentry = { version = "0.17.0", optional = true }
faster-hex = { version = "0.4", optional = true }
ckb-hash = {path = "../util/hash", version = "= 0.39.0-pre"}
secp256k1 = {version = "0.19", features = ["recovery"], optional = true }
trust-dns-resolver = { version = "0.19", optional = true }
snap = "1"
ckb-types = { path = "../util/types", version = "= 0.39.0-pre" }
ipnetwork = "0.14"
serde_json = "1.0"
bloom-filters = "0.1"
ckb-spawn = { path = "../util/spawn", version = "= 0.39.0-pre" }

# TODO use features to enable tokio runtime ???
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
p2p = { version="0.3.3", package="tentacle", default-features=false, features = ["molc"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
p2p = { version="0.3.3", package="tentacle", default-features=false, features = ["molc", "wasm-timer"] }

[features]
with_sentry = ["sentry"]
with_dns_seeding = ["lazy_static", "bs58", "faster-hex", "trust-dns-resolver", "secp256k1"]

[dev-dependencies]
tempfile = "3.0"
criterion = "0.3"
proptest = "0.9"
num_cpus = "1.10"

[[bench]]
name = "peer_store"
harness = false
path = "src/benches/peer_store.rs"
